name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        julia-version: ["1.6", "1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Run Pkg.build
        uses: julia-actions/julia-buildpkg@v1
      - name: Restore Project.toml
        run: git restore Project.toml
      - name: Run Julia package tests
        uses: julia-actions/julia-runtest@v1
#      - name: Compute test coverage
#        uses: julia-actions/julia-processcoverage@v1
#      - name: Report coverage
#        uses: codecov/codecov-action@v3
